name: Bug Report
description: Report a Ruri bug
title: "[Bug]: "
labels: "bug :beetle:"
body:
- type: checkboxes
  attributes:
    label: Preflight Checklist
    description: Please ensure you've completed all of the following.
    options:
      - label: I use the latest version of Ruri.
        required: true
      - label: I have searched this repository's issue tracker for a matching report, without success.
        required: true
      - label: I understand that Ruri has NO affiliation with Google, YouTube, Pear Desktop, or Glassy Music.
        required: true
- type: input
  id: app-version
  attributes:
    label: Ruri version
    description: |
      What version of Ruri are you using? Check if the issue still happens on the latest build.
    placeholder: 0.1.0
  validations:
    required: true
- type: checkboxes
  attributes:
    label: Checklists
    options:
      - label: I use a portable build.
      - label: I can reproduce this issue in the [official web YouTube Music](https://music.youtube.com).
- type: dropdown
  id: os
  attributes:
    label: What operating system are you using?
    options:
      - Windows
      - macOS
      - Ubuntu
      - Other Linux
      - Other (specify below)
  validations:
    required: true
- type: input
  id: os-version
  attributes:
    label: Operating System Version
    description: Windows — Start > Settings > System > About. macOS — Apple menu > About This Mac. Linux — lsb_release or uname -a.
    placeholder: "e.g. Windows 11, macOS 15, Ubuntu 24.04"
  validations:
    required: true
- type: dropdown
  id: cpu-arch
  attributes:
    label: What CPU architecture are you using?
    options:
      - x64
      - ia32
      - arm64 (including Apple Silicon)
      - Other (specify below)
  validations:
    required: true
- type: input
  attributes:
    label: Last known working Ruri version
    description: (If applicable) Last version where this still worked.
    placeholder: 0.1.0
- type: textarea
  attributes:
    label: Reproduction steps
    description: Provide steps to reproduce the issue.
    placeholder: 1. Enable the X plugin.
  validations:
    required: true
- type: textarea
  attributes:
    label: Expected Behavior
    description: A clear and concise description of what you expected to happen.
    validations:
    required: true
- type: textarea
  attributes:
    label: Actual Behavior
    description: A clear description of what actually happens.
    validations:
    required: true
- type: textarea
  id: enabled-plugins
  attributes:
    label: Enabled plugins
    description: Provide the list of plugins you enabled.
    placeholder: 1. Album Color Theme
  validations:
    required: true
- type: textarea
  attributes:
    label: Additional Information
    description: Extra context, logs, or screenshots.
