name: Feature Request
description: Suggest an idea for Ruri
title: "[Feature Request]: "
labels: "enhancement :sparkles:"
body:
- type: checkboxes
  attributes:
    label: Preflight Checklist
    description: Please ensure you've completed all of the following.
    options:
      - label: I use the latest version of Ruri.
        required: true
      - label: I have searched this repository's issue tracker for a matching request, without success.
        required: true
- type: textarea
  attributes:
    label: Problem Description
    description: A clear and concise description of the problem you are seeking to solve.
  validations:
    required: true
- type: textarea
  attributes:
    label: Proposed Solution
    description: Describe the solution you'd like.
  validations:
    required: true
- type: textarea
  attributes:
    label: Alternatives Considered
    description: Other approaches you thought about.
  validations:
    required: true
- type: textarea
  attributes:
    label: Additional Information
    description: Screenshots, mocks, or extra context.
  validations:
    required: false
